import Head from "next/head";
import PanelHeading from "../components/Panel/PanelHeading";
import TabGroup from "../components/Panel/TabGroup";

const HeadLine = "WELCOME!";
var NameTabs = [
  {
    urlpath: "#",
    tabname: "Theory",
  },
  {
    urlpath: "#",
    tabname: "Practice",
  },
];

function Theory() {
  return (
    // REPLACE YOUR THEORY BY THE CONTENT & DESIRED MARKDOWN PREFERENCES
    <>Theory</>
  );
}
function Question() {
  return (
    // REPLACE YOUR QUESTION BY THE CONTENT & DESIRED MARKDOWN PREFERENCES
    <>Question</>
  );
}

var subContent = [<Theory key={1} />, <Question key={2} />];


export default function Home(index) {
  return (
    <div>
      <Head>
        <title>BurpShark | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PanelHeading>{HeadLine}</PanelHeading>
      <TabGroup
        tabsTitle={NameTabs}
        tabsPanelobject={subContent}
        defIndex={0}
      ></TabGroup>
    </div>
  );
}
